matrix:
  allow_failures:
    - env: CABALVER=head GHCVER=head

env:
 - CABALVER=1.22 GHCVER=7.10.1
 - CABALVER=1.24 GHCVER=8.0.1
 - CABALVER=head GHCVER=head

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER libicu-dev
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-$CABALVER update
 - travis_retry sudo apt-get install happy-1.19.5 alex-3.1.7
 - export PATH=/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH

script:
 - travis_retry cabal-$CABALVER install -j2 --enable-tests --only-dependencies --reorder-goals
 - cabal-$CABALVER install -j1 --enable-tests
 - cabal-$CABALVER test

notifications:
  irc: "chat.freenode.net#yi"
